jumps: 1440
start_date: "2018-17-09"
end_date: "2024-16-09"
root: "./data"
# data_path: "./btcusd_1-min_data.csv"
data_path: "./Dataset_daily.csv"
# train_ratio: 0.8
# test_ratio: 0.1
train_interval: ["2018-17-09", "2022-17-09"]
val_interval: ["2022-17-09", "2023-17-09"]
test_interval: ["2023-17-09", "2024-17-09"]
# window_size: 14